version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project/BlogPostValidation
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports/junitreports # Ensure this is the correct path for your test results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - store_artifacts:
          path: Reports/ # Ensure this is the correct directory for your Extent Report
          destination: extent-reports
          
workflows:
  build-and-test:
    jobs:
      - test-java
